sudo: required 
language: generic 
services: 
  - docker 
before_install:
  - docker build -t eanene/react-app1 -f Dockerfile.dev . 
script:
  - docker run -e CI=true eanene/react-app1 npm run test

deploy:
  provider: elasticbeanstalk 
  region: "us-east-2" 
  app: "docker2"
  env: "Docker2-env"
  bucket_name: "elasticbeanstalk-us-east-2-311987416908" 
  bucket_path: "docker2" 
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
