sudo: required 
services: 
  - docker 
before_install:
  - docker build -t eanene/react-app:travisversion -f Dockerfile.dev . 
script:
  - docker run eanene/react-app:travisversion npm run test -- --coverage 