sudo: required 
language: generic 
services: 
  - docker 
before_install:
  - docker build -t eanene/react-app:travisversion -f Dockerfile.dev . 
script:
  - docker run -e CI=true eanene/react-app:travisversion npm run test 

deploy:
  provider: elasticbeanstalk 
  region: "us-east-2" 
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-311987416908" 
  bucket_path: "docker" 
  on: 
    branch: master 
  access_key_id: $AWS_ACCES_KEY 
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"
